site_name: lib
site_description: IT projects and resources.. along the way..
site_author: mbiscarra
docs_dir: docs/
theme:
  name: ivory
nav:  
- index.md
- Openshift VS Kubernetes introduction.md
- From Java EE To Cloud Native javaee-to-cloud-native.md
- Microservices FAQ & Kubernetes Native faq.md
- sre.md
- serverless.md
- DevOps
    - DevOps devops.md
    - Cheat Sheets cheatsheets.md
    - GitOps gitops.md
    - Demos & Screencasts. OpenShift, Kubernetes, Jenkins Pipelines with JCasC and more  demos.md
