name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install mkdocs
        python -m pip install mkdocs-ivory
    - name: Deploy Files
      run: |
        git remote add gh-token "https://github.com/melvinpetix/lib.git"
        python -m mkdocs gh-deploy
