name: Build Documentation using MkDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          CONFIG_FILE: /mkdocs.yml
          EXTRA_PACKAGES: build-base
  
